/*
 * Introduction to Java Concurrency
 * 
 * https://github.com/egalli64/jaco
 */
package com.example.jaco.m3.s8;

import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.atomic.DoubleAdder;
import java.util.stream.Stream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * CyclicBarrier
 */
public class Barrier extends ProblemFrame {
    private static final Logger log = LoggerFactory.getLogger(Barrier.class);

    /**
     * Create a CyclicBarrier for the workers and the main thread. Create a thread
     * for each worker and start them. Each worker does its job and waits on the
     * barrier.
     * <p>
     * The main thread wait for the barrier to break, then check for the result
     * generated by the workers.
     * 
     * @param args not used
     */
    public static void main(String[] args) {
        log.trace("Enter");
        CyclicBarrier barrier = new CyclicBarrier(TASK_NR + 1);
        DoubleAdder accumulator = new DoubleAdder();

        Runnable worker = () -> {
            log.trace("Enter");

            double value = adder(100);
            log.debug("Value is {}", value);
            accumulator.add(value);
            try {
                barrier.await();
            } catch (InterruptedException | BrokenBarrierException ex) {
                log.warn("Wait on barrier interrupted", ex);
            }

            log.trace("Exit");
        };

        Stream.generate(() -> new Thread(worker)).limit(TASK_NR).forEach(Thread::start);

        try {
            barrier.await();
        } catch (InterruptedException | BrokenBarrierException ex) {
            log.warn("Wait on barrier interrupted", ex);
        }

        System.out.printf("Total: %f\n", accumulator.sum());
        log.trace("Exit");
    }
}
